### ISSUE TITLE
Karma sourcemaps

### ISSUE THREAD

**Issue by Xesenix** [Xesenix/xes-webpack-core#1]
Setting `webpack.devtool = 'cheap-module-source-map'` shows unreadable paths while debugging tests.

For example:
```
TypeError: undefined is not a function
  at <Jasmine>
  at MovementSystem.resolveCell (src/game-00/main.test.ts:215759:13)
  at ordered.filter.obj (src/game-00/main.test.ts:215718:42)
  ...
```

And without it (so probably `'cheap-eval-source-map'`)
```
TypeError: undefined is not a function
  at <Jasmine>
  at MovementSystem.resolveCell (webpack-internal:///./src/lib/game/ancient-maze/system/movement.system.ts:135:13)
  at ordered.filter.obj (webpack-internal:///./src/lib/game/ancient-maze/system/movement.system.ts:94:42)
```

**Comment by Xesenix** [comment]
This conflicts with https://reactjs.org/docs/cross-origin-errors.html more specifically this:
```
Some JavaScript bundlers may wrap the application code with eval statements in development. (For example Webpack will do this if devtool is set to any value containing the word “eval”.) This may cause errors to be treated as cross-origin.
```

**Comment by Xesenix** [comment]
Check if that helps: https://github.com/webpack-contrib/karma-webpack/issues/109#issuecomment-224961264
